import os
import secrets

APP_SECRET_KEY = secrets.APP_SECRET_KEY
AUTH0_CLIENT_ID = secrets.AUTH0_CLIENT_ID
AUTH0_CLIENT_SECRET = secrets.AUTH0_CLIENT_SECRET
AUTH0_DOMAIN = secrets.AUTH0_DOMAIN
AWS_ACCESS_KEY_ID = secrets.AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = secrets.AWS_SECRET_ACCESS_KEY


# APP_SECRET_KEY = os.getenv("APP_SECRET_KEY")
# AUTH0_CLIENT_ID = os.getenv("AUTH0_CLIENT_ID")
# AUTH0_CLIENT_SECRET = os.getenv("AUTH0_CLIENT_SECRET")
# AUTH0_DOMAIN = os.getenv("AUTH0_DOMAIN")

# AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
# AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")

# data_store = ReplitDataStore()
